services:

  spring:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: ./user-service-spring
    ports:
      - "8081:8081"

  node:
    build: ./event-venue-service-node
    ports:
      - "3000:3000"
    env_file:
      - ./event-venue-service-node/.env.docker

  dotnet:
    build: ./vendor-budget-service-dotnet
    ports:
      - "5180:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  react:
    build: ./eventzen-ui
    ports:
      - "3001:3001"