services:

  spring:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: ./user-service-spring
    ports:
      - "8081:8081"

  node:
    build: ./event-venue-service-node
    ports:
      - "3000:3000"

  dotnet:
    build: ./vendor-budget-service-dotnet
    ports:
      - "5180:8080"

  react:
    build: ./eventzen-ui
    ports:
      - "3001:3001"