spring.datasource.url=jdbc:mysql://localhost:3306/eventzen_db
spring.datasource.username=root
spring.datasource.password=S@kshi19

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

node.url=http://localhost:3000/api

server.port=8081

management.endpoints.web.exposure.include=*